### ISSUE TITLE
Will there be a version release for the latest changes?

### ISSUE THREAD

**Issue by dpwilhelmsen** [yosymfony/resource-watcher#6]
I noticed that a few days ago support for Symfony 4 was added. Will there be an upcoming version bump to include these changes? Thanks for your work!

**Comment by yosymfony** [comment]
yes. I plan on doing additional changes in coming days.

**Comment by dpwilhelmsen** [comment]
@yosymfony Excellent. I'll keep an eye out then.

**Comment by yosymfony** [comment]
At the end, I made a release with just Symfony 4 support. My changes will come next.

**Comment by dpwilhelmsen** [comment]
Thanks!
